export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';

export const FETCH_COURSES = 'FETCH_COURSES';
export const ADD_COURSE = "ADD_COURSE";
export const ADD_COURSE_ERROR = "ADD_COURSE_ERROR";

export const FETCH_ASSIGNMENT = 'FETCH_ASSIGNMENT';
export const ADD_ASSIGNMENT = "ADD_ASSIGNMENT";
export const ADD_ASSIGNMENT_ERROR = "ADD_ASSIGNMENT_ERROR";
